name: news-tomorrow-backend
region: nyc

services:
  - name: api
    github:
      repo: paul-hanna/paul-hanna.github.io
      branch: main
      deploy_on_push: true
    source_dir: backend
    build_command: npm install
    run_command: npm start
    environment_slug: node-js
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 8080
    routes:
      - path: /
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "8080"
      - key: DB_HOST
        scope: RUN_TIME
        type: SECRET
      - key: DB_PORT
        scope: RUN_TIME
        type: SECRET
      - key: DB_NAME
        scope: RUN_TIME
        type: SECRET
      - key: DB_USER
        scope: RUN_TIME
        type: SECRET
      - key: DB_PASSWORD
        scope: RUN_TIME
        type: SECRET
      - key: DB_SSL
        value: "true"
      - key: OPENAI_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: ANTHROPIC_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: OPENROUTER_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: NEWS_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: AI_PROVIDER
        scope: RUN_TIME
        type: SECRET
      - key: OPENAI_MODEL
        scope: RUN_TIME
        type: SECRET

