import { get, set, subscribe, currentCart, setCart, currentLocation } from './state.js';
import { CATEGORIES, PRODUCTS, PRODUCTS_BY_ID, BUNDLES, isAvailable, bundleAvailable, ratingFor, reviewsFor, metaFor, hash } from './data.js';
import { addItem, setQty, applyBundle, bundlePrice, bundleWasPrice, totals, isEmpty, itemCount } from './cart.js';
import { money, basisLabel, qtyLabel } from './format.js';
import { icon } from './icons.js';
import { play } from './audio.js';
import { showToast } from './toast.js';

const $ = (id) => document.getElementById(id);

// Photography is generated by scripts/fetch-images.py. A product whose fetch failed
// simply has no file; the card falls back to the line icon rather than showing a
// broken image, so a missing photo degrades instead of breaking the grid.
// Catalog names reach HTML attributes, and one product is literally named
// AGM-114R9X "Ninja" — with the quotes. Interpolating that raw truncates the
// attribute at the first quote and spills the rest out as bareword attributes.
// Every catalog string bound into an attribute goes through here.
function attr(value) {
  return String(value).replace(/[&<>"']/g, (c) => (
    { '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]
  ));
}

function media(kind, id, name, iconName) {
  const src = `assets/${kind}/${id}.jpg`;
  return `<div class="card-media">
    <img src="${attr(src)}" alt="${attr(name)}" width="600" height="400" loading="lazy"
         onerror="this.closest('.card-media').classList.add('no-photo'); this.remove();">
    <span class="card-media-fallback">${icon(iconName)}</span>
  </div>`;
}

function ratingHtml(productId) {
  const { rating, count } = ratingFor(productId);
  return `<div class="card-rating"><span class="star">${icon('star')}</span>${rating.toFixed(1)} · ${count.toLocaleString('en-US')} reviews</div>`;
}

function controlHtml(product, qty) {
  if (!qty) return `<button class="btn-add" type="button" data-add="${product.id}" aria-label="Add ${attr(product.name)}">+</button>`;
  return `<div class="stepper" data-stepper="${product.id}">
    <button class="stepper-btn" type="button" data-delta="-1" aria-label="Less">−</button>
    <span class="stepper-qty">${qtyLabel(product, qty)}</span>
    <button class="stepper-btn" type="button" data-delta="1" aria-label="More">+</button>
  </div>`;
}

function productCard(product, loc, cart) {
  const avail = isAvailable(product, loc);
  const qty = cart.items[product.id] || 0;
  const minNote = product.minQty > 1 ? ` · min ${qtyLabel(product, product.minQty)}` : '';
  return `<article class="card ${avail ? '' : 'unavailable'}" data-product="${product.id}">
    ${media('products', product.id, product.name, product.icon)}
    <h3 class="card-name">${product.name}</h3>
    <p class="card-spec">${product.spec}${minNote}</p>
    <p class="card-meta">${avail ? metaFor(product) : (loc.partner ? 'Fulfilled by partner only' : 'Outside fulfillment range')}</p>
    ${ratingHtml(product.id)}
    <div class="card-foot">
      <span class="price">${money(product.price)} <small>${basisLabel(product.basis)}</small></span>
      ${avail ? controlHtml(product, qty) : '<span>Not available in your area</span>'}
    </div>
  </article>`;
}

function bundleCard(bundle, loc) {
  const avail = bundleAvailable(bundle, loc);
  const price = bundlePrice(bundle, PRODUCTS_BY_ID);
  const was = bundleWasPrice(bundle, PRODUCTS_BY_ID);
  const pct = Math.round((1 - price / was) * 100);
  const items = Object.entries(bundle.items).map(([id, q]) => `${qtyLabel(PRODUCTS_BY_ID[id], q)} ${PRODUCTS_BY_ID[id].name}`).join(' · ');
  return `<article class="card bundle ${avail ? '' : 'unavailable'}" data-bundle="${bundle.id}">
    ${avail ? `<span class="bundle-save">Save ${pct}%</span>` : ''}
    ${media('bundles', bundle.id, bundle.name, bundle.icon)}
    <h3 class="card-name">${bundle.name}</h3>
    <p class="card-spec">${bundle.tagline}</p>
    <p class="bundle-items">${items}</p>
    ${ratingHtml(bundle.id)}
    <div class="card-foot">
      <span class="price"><span class="bundle-was">${money(was)}</span>${money(price)}</span>
      ${avail ? `<button class="btn-add" type="button" data-add-bundle="${bundle.id}" aria-label="Add ${attr(bundle.name)}">+</button>` : '<span>Not available in your area</span>'}
    </div>
  </article>`;
}

function renderBanner(loc) {
  $('storeBanner').innerHTML = `
    <span class="banner-icon">${icon('pin')}</span>
    <div><strong>${loc.name}, ${loc.country}</strong><br><span class="muted">Fulfilled by ${loc.fulfilledBy} · est. ${loc.eta}${loc.partner ? ' · Fulfilled by partner' : ''}</span></div>
    <button class="btn-link" type="button" id="changeLoc">Change</button>`;
  $('changeLoc').addEventListener('click', () => set({ view: 'landing' }));
}

function renderChips(state) {
  $('chips').innerHTML = CATEGORIES.map((c) =>
    `<button class="chip ${state.category === c.id ? 'active' : ''}" type="button" role="tab" data-category="${c.id}">${c.label}</button>`).join('');
}

function renderGrid(state) {
  const loc = currentLocation();
  const cart = currentCart();
  let html;
  if (state.category === 'bundles') {
    const sorted = [...BUNDLES].sort((a, b) => Number(bundleAvailable(b, loc)) - Number(bundleAvailable(a, loc)));
    html = sorted.map((b) => bundleCard(b, loc)).join('');
  } else {
    const list = PRODUCTS.filter((p) => p.category === state.category)
      .sort((a, b) => Number(isAvailable(b, loc)) - Number(isAvailable(a, loc)));
    html = list.map((p) => productCard(p, loc, cart)).join('');
  }
  $('grid').innerHTML = html;
}

function renderStore(state) {
  if (state.view !== 'store') return;
  const loc = currentLocation();
  if (!loc) { set({ view: 'landing' }); return; }
  renderBanner(loc);
  renderChips(state);
  renderGrid(state);
  // Delivery apps surface the cart as a persistent bar on small screens rather than
  // making the user reach for the header. Hidden entirely when the cart is empty.
  const bar = $('cartBar');
  const cart = currentCart();
  const t = totals(cart, PRODUCTS_BY_ID);
  bar.hidden = isEmpty(cart);
  $('cartBarCount').textContent = String(itemCount(cart));
  $('cartBarTotal').textContent = money(t.total);
}

// ---------- Sheet ----------
function alsoOrdered(product, loc) {
  const pool = PRODUCTS.filter((p) => p.id !== product.id && isAvailable(p, loc));
  const h = hash(product.id + ':also');
  const picks = [];
  for (let i = 0; picks.length < 3 && i < pool.length; i++) {
    const p = pool[(h + i * 5) % pool.length];
    if (!picks.includes(p)) picks.push(p);
  }
  return picks;
}

function renderSheet(state) {
  const id = state.sheetProductId;
  const open = Boolean(id);
  $('sheet').hidden = !open;
  $('sheetBackdrop').hidden = !open;
  if (!open) return;
  const product = PRODUCTS_BY_ID[id];
  const loc = currentLocation();
  const cart = currentCart();
  const qty = cart.items[id] || 0;
  const avail = isAvailable(product, loc);
  const reviews = reviewsFor(id);
  const { rating, count } = ratingFor(id);
  $('sheetBody').innerHTML = `
    ${media('products', product.id, product.name, product.icon)}
    <h2 id="sheetTitle">${product.name}</h2>
    <div class="card-rating"><span class="star">${icon('star')}</span>${rating.toFixed(1)} · ${count.toLocaleString('en-US')} reviews</div>
    <ul class="spec-list">
      <li><strong>Spec:</strong> ${product.spec}</li>
      <li><strong>Ships from:</strong> ${product.shipsFrom}</li>
      <li><strong>Sold:</strong> ${basisLabel(product.basis)}${product.minQty > 1 ? `, minimum ${qtyLabel(product, product.minQty)}` : ''}</li>
      <li><strong>Price basis:</strong> FY${product.fy}, ${product.source}</li>
      <li><strong>${metaFor(product)}</strong></li>
    </ul>
    <div class="card-foot">
      <span class="price">${money(product.price)} <small>${basisLabel(product.basis)}</small></span>
      ${avail ? controlHtml(product, qty) : '<span>Not available in your area</span>'}
    </div>
    <div class="reviews">
      ${reviews.map((r) => `<div class="review"><div class="stars">${icon('star').repeat(r.stars)}</div><p>${r.text}</p><span class="sig">${r.signature}</span></div>`).join('')}
    </div>
    <div class="also">
      <h3>Customers also ordered</h3>
      <div class="also-row">${alsoOrdered(product, loc).map((p) => `<button class="also-chip" type="button" data-open="${p.id}">${p.name}<br><small>${money(p.price)}</small></button>`).join('')}</div>
    </div>`;
}

// ---------- Actions ----------
function changeQty(productId, delta) {
  const product = PRODUCTS_BY_ID[productId];
  const cart = currentCart();
  const current = cart.items[productId] || 0;
  const next = current + delta * product.step;
  setCart(setQty(cart, product, next));
  play(next <= 0 ? 'thunk' : 'tick');
}

function handleClick(evt) {
  const add = evt.target.closest('[data-add]');
  if (add) {
    evt.stopPropagation();
    setCart(addItem(currentCart(), PRODUCTS_BY_ID[add.dataset.add]));
    play('pop');
    return;
  }
  const addBundle = evt.target.closest('[data-add-bundle]');
  if (addBundle) {
    evt.stopPropagation();
    const bundle = BUNDLES.find((b) => b.id === addBundle.dataset.addBundle);
    setCart(applyBundle(currentCart(), bundle, PRODUCTS_BY_ID));
    play('pop');
    showToast(`${bundle.name} added to your order`);
    return;
  }
  const step = evt.target.closest('[data-delta]');
  if (step) {
    evt.stopPropagation();
    changeQty(step.closest('[data-stepper]').dataset.stepper, Number(step.dataset.delta));
    return;
  }
  const open = evt.target.closest('[data-open]');
  if (open) { play('click'); set({ sheetProductId: open.dataset.open }); return; }
  const card = evt.target.closest('[data-product]');
  if (card && !card.classList.contains('unavailable')) { play('click'); set({ sheetProductId: card.dataset.product }); }
}

export function initStore() {
  $('chips').addEventListener('click', (evt) => {
    const chip = evt.target.closest('[data-category]');
    if (chip) { play('click'); set({ category: chip.dataset.category }); }
  });
  $('grid').addEventListener('click', handleClick);
  $('sheetBody').addEventListener('click', handleClick);
  $('cartBar').addEventListener('click', () => { play('click'); set({ drawerOpen: true }); });
  const closeSheet = () => set({ sheetProductId: null });
  $('sheetClose').innerHTML = icon('close');
  $('sheetClose').addEventListener('click', closeSheet);
  $('sheetBackdrop').addEventListener('click', closeSheet);
  document.addEventListener('keydown', (e) => { if (e.key === 'Escape' && get().sheetProductId) closeSheet(); });
  subscribe((state) => { renderStore(state); renderSheet(state); });
  renderStore(get());
  renderSheet(get());
}
